AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Small Express app deployed with AWS SAM (Lambda + HTTP API)

Globals:
  Function:
    Runtime: nodejs22.x
    Timeout: 20           # seconds
    MemorySize: 512
    Architectures:
      - x86_64

Resources:
  ExpressHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowOrigins:
          - "*"
        AllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        AllowHeaders:
          - "*"

  ExpressFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/
      Handler: lambda.handler    # lambda.js exports.handler
      Description: Express app behind HTTP API
      Events:
        Root:
          Type: HttpApi
          Properties:
            ApiId: !Ref ExpressHttpApi
            Path: /
            Method: ANY
        ProxyApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref ExpressHttpApi
            Path: /{proxy+}
            Method: ANY

  StaticWebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  StaticWebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref StaticWebsiteBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowCloudFrontServicePrincipalGetObject
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource:
              !Join
                - ''
                - - !GetAtt StaticWebsiteBucket.Arn
                  - '/*'
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}"

  CloudFrontOAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub "${AWS::StackName}-oac"
        Description: Access control for S3 origin
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        HttpVersion: http2
        PriceClass: PriceClass_100

        Origins:
          - Id: S3Origin
            DomainName: !GetAtt StaticWebsiteBucket.RegionalDomainName
            S3OriginConfig: {}     # required for S3 origins
            OriginAccessControlId: !Ref CloudFrontOAC

        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [GET, HEAD]
          Compress: true
          # Managed "CachingDisabled" policy (no caching: all TTLs = 0)
          # https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/using-managed-cache-policies.html
          CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad         
          OriginRequestPolicyId: 88a5eaf4-2fd4-4709-b370-b4c650ea3fcf  # AWS managed CORS-S3Origin

        ViewerCertificate:
          CloudFrontDefaultCertificate: true

Outputs:
  ApiBaseUrl:
    Description: Base URL for the Express HTTP API
    Value: !Sub "https://${ExpressHttpApi}.execute-api.${AWS::Region}.amazonaws.com"
  ExpressFunctionArn:
    Description: ARN of the Lambda function running Express
    Value: !GetAtt ExpressFunction.Arn
  CloudFrontDomainName:
    Description: CloudFront distribution domain
    Value: !GetAtt CloudFrontDistribution.DomainName
  BucketName:
    Description: Name of the static site bucket
    Value: !Ref StaticWebsiteBucket